name: CI (Cross Platform)

on: push

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v4
      - name: apt
        run: sudo apt install ninja-build libgtest-dev
      - name: cmake
        run: cmake --preset debug
      - name: cmake --build
        run: cmake --build build/debug --target tests
      - name: cpack
        run: cpack --config build/debug/CPackConfig.cmake -B build/debug
      - name: tests
        working-directory: build/debug
        run: tests
      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: hla-latest-debug
          path: build/debug/HLA-*.tar.gz
