name: CI (Ubuntu Debug)

on: push

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v4
      - name: apt
        run: sudo apt install ninja-build libgtest-dev
      - name: cmake
        run: cmake --preset debug
      - name: cmake --build
        run: cmake --build --preset debug --target tests
      - name: cpack
        working-directory: build/debug
        run: cpack
      - name: ctest
        working-directory: build/debug/targets/tests
        run: ctest
      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: hla-latest-debug
          path: build/debug/HLA-*.tar.gz
